# Generated by Django 4.2 on 2023-05-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjpeg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secfile',
            name='sec_file',
            field=models.FileField(upload_to='sec_file/'),
        ),
    ]
